# Following Documentation for labeler GitHub Action
# Found Here: https://github.com/actions/labeler

# add 'release' label to any PR opened against main from a 'release-#.#.#'' branch
release:
  - all:
    - base-branch: ['main']
    - head-branch: ['release-[0-9]+\.[0-9]+\.[0-9]+']

# add 'feature' label to any PR that begins with feature:
feature:
  - head-branch: ['^feature:']

# add 'bug' label to any PR that begins with bug:
bug:
  - head-branch: ['^bug:']

# add 'documentation' label to any PR that begins with docs:
documentation:
  - head-branch: ['^docs:']

# add 'refactor' label to any PR that begins with refactor:
refactor:
  - head-branch: ['^refactor:']

# add 'internal' label to any PR that begins with internal:
internal:
  - head-branch: ['^internal:']
