# Following Documentation for GitHub Action release-drafter, and other repos
# Action: https://github.com/marketplace/actions/release-drafter
# Other Repos: https://github.com/sanders41/meilisearch-fastapi/blob/main/.github/release-draft-template.yaml

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'documentation'
      - 'bug'
      - 'refactor'
      - 'internal'
  default: patch
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
      - 'major'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Internal'
    labels:
      - 'refactor'
      - 'internal'
template: |
  ## Changes

  $CHANGES
