version: '3.3'

services:
  svar-db:
    image: postgres:alpine
    user: postgres
    restart: always
    ports:
      - "${POSTGRES_SERVER_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
